In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [3]:
#!wget $data

In [4]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [7]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
categorial_columns = list(df.dtypes[df.dtypes == 'object'].index)
for c in categorial_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [8]:
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.5,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes

In [9]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [10]:
df['totalcharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: totalcharges, Length: 7043, dtype: object

In [11]:
tc = pd.to_numeric(df['totalcharges'], errors='coerce')

In [12]:
df['totalcharges'] = pd.to_numeric(df['totalcharges'], errors='coerce')

In [13]:
df['totalcharges'].fillna(0, inplace=True)

/tmp/ipykernel_2063/3851262413.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['totalcharges'].fillna(0, inplace=True)

In [14]:
df.churn = (df.churn == 'yes').astype(int)

In [15]:
df.churn.value_counts()

churn
0    5174
1    1869
Name: count, dtype: int64

In [16]:
#setting up the validation framework

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [19]:
len(df_full_train), len(df_test)

(5634, 1409)

In [20]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [21]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [22]:
df_train

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
3897,8015-ihcgw,female,0,yes,yes,72,yes,yes,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,electronic_check,115.50,8425.15,0
1980,1960-uycnn,male,0,no,no,10,yes,yes,fiber_optic,no,...,yes,no,no,yes,month-to-month,yes,electronic_check,95.25,1021.55,0
6302,9250-wypll,female,0,no,no,5,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,no,electronic_check,75.55,413.65,1
727,6786-obwqr,female,0,yes,yes,5,yes,no,fiber_optic,no,...,no,no,yes,no,month-to-month,yes,electronic_check,80.85,356.10,0
5104,1328-euzhc,female,0,yes,no,18,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.10,370.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3774,1309-xgfsn,male,1,yes,yes,52,yes,yes,dsl,no,...,yes,no,yes,yes,one_year,yes,electronic_check,80.85,4079.55,0
6108,4819-hjpiw,male,0,no,no,18,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,no,mailed_check,25.15,476.80,0
1530,3703-vavcl,male,0,yes,yes,2,yes,no,fiber_optic,no,...,yes,yes,no,yes,month-to-month,no,credit_card_(automatic),90.00,190.05,1
3701,3812-lrzir,female,0,yes,yes,27,yes,yes,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,electronic_check,24.50,761.95,0
4368,1704-nrwye,female,1,no,no,9,yes,no,fiber_optic,no,...,no,no,yes,no,month-to-month,yes,electronic_check,80.85,751.65,1

In [23]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [24]:
df_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,8015-ihcgw,female,0,yes,yes,72,yes,yes,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,electronic_check,115.50,8425.15,0
1,1960-uycnn,male,0,no,no,10,yes,yes,fiber_optic,no,...,yes,no,no,yes,month-to-month,yes,electronic_check,95.25,1021.55,0
2,9250-wypll,female,0,no,no,5,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,no,electronic_check,75.55,413.65,1
3,6786-obwqr,female,0,yes,yes,5,yes,no,fiber_optic,no,...,no,no,yes,no,month-to-month,yes,electronic_check,80.85,356.10,0
4,1328-euzhc,female,0,yes,no,18,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.10,370.50,0

In [25]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [26]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [27]:
#EDA

In [28]:
df_full_train = df_full_train.reset_index(drop=True)

In [29]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [30]:
df_full_train.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [31]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [32]:
categorial_columns = [c for c in df.columns if c not in numerical]

In [33]:
categorial_columns.remove('customerid')
categorial_columns.remove('churn')

In [34]:
df_full_train[categorial_columns].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [35]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()
churn_global = df_full_train.churn.mean()

In [36]:
print(f"churn_female: {churn_female}")
print(f"churn_male: {churn_male}")
print(f"churn_global: {churn_global}")

churn_female: 0.27682403433476394
churn_male: 0.2632135306553911
churn_global: 0.26996805111821087

In [37]:
churn_nopartner = df_full_train[df_full_train.partner == 'no'].churn.mean()
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()

print(f"churn_nopartner: {churn_nopartner}")
print(f"churn_partner: {churn_partner}")

churn_nopartner: 0.3298090040927694
churn_partner: 0.20503330866025166

In [38]:
#risk ratio

In [39]:
churn_nopartner/churn_global

np.float64(1.2216593879412643)

In [40]:
!pip install Ipython

Requirement already satisfied: Ipython in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (9.6.0)
Requirement already satisfied: decorator in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (2.19.2)
Requirement already satisfied: stack_data in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from Ipython) (5.14.3)
Requirement already satisfied: wcwidth in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->Ipython) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from jedi>=0.16->Ipython) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from pexpect>4.3->Ipython) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from stack_data->Ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from stack_data->Ipython) (3.0.0)
Requirement already satisfied: pure-eval in /workspaces/ML-Zoomcamp/.venv/lib/python3.12/site-packages (from stack_data->Ipython) (0.2.3)

In [41]:
for c in categorial_columns:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - churn_global
    df_group['risk_ratio'] = df_group['mean'] / churn_global
    display(df_group.sort_values('risk_ratio'))
    print()
    print()

gender

            mean  count      diff  risk_ratio
gender
male    0.263214   2838 -0.006755    0.974980
female  0.276824   2796  0.006856    1.025396

seniorcitizen

                   mean  count      diff  risk_ratio
seniorcitizen
0              0.242270   4722 -0.027698    0.897403
1              0.413377    912  0.143409    1.531208

partner

             mean  count      diff  risk_ratio
partner
yes      0.205033   2702 -0.064935    0.759472
no       0.329809   2932  0.059841    1.221659

dependents

                mean  count      diff  risk_ratio
dependents
yes         0.165666   1666 -0.104302    0.613651
no          0.313760   3968  0.043792    1.162212

phoneservice

                  mean  count      diff  risk_ratio
phoneservice
no            0.241316    547 -0.028652    0.893870
yes           0.273049   5087  0.003081    1.011412

multiplelines

                      mean  count      diff  risk_ratio
multiplelines
no_phone_service  0.241316    547 -0.028652    0.893870
no                0.257407   2700 -0.012561    0.953474
yes               0.290742   2387  0.020773    1.076948

internetservice

                     mean  count      diff  risk_ratio
internetservice
no               0.077805   1221 -0.192163    0.288201
dsl              0.192347   1934 -0.077621    0.712482
fiber_optic      0.425171   2479  0.155203    1.574895

onlinesecurity

                         mean  count      diff  risk_ratio
onlinesecurity
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.153226   1612 -0.116742    0.567570
no                   0.420921   2801  0.150953    1.559152

onlinebackup

                         mean  count      diff  risk_ratio
onlinebackup
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.217232   1915 -0.052736    0.804660
no                   0.404323   2498  0.134355    1.497672

deviceprotection

                         mean  count      diff  risk_ratio
deviceprotection
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.230412   1940 -0.039556    0.853480
no                   0.395875   2473  0.125907    1.466379

techsupport

                         mean  count      diff  risk_ratio
techsupport
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.159926   1632 -0.110042    0.592390
no                   0.418914   2781  0.148946    1.551717

streamingtv

                         mean  count      diff  risk_ratio
streamingtv
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.302723   2167  0.032755    1.121328
no                   0.342832   2246  0.072864    1.269897

streamingmovies

                         mean  count      diff  risk_ratio
streamingmovies
no_internet_service  0.077805   1221 -0.192163    0.288201
yes                  0.307273   2200  0.037305    1.138182
no                   0.338906   2213  0.068938    1.255358

contract

                    mean  count      diff  risk_ratio
contract
two_year        0.028274   1344 -0.241694    0.104730
one_year        0.120573   1186 -0.149395    0.446621
month-to-month  0.431701   3104  0.161733    1.599082

paperlessbilling

                      mean  count      diff  risk_ratio
paperlessbilling
no                0.172071   2313 -0.097897    0.637375
yes               0.338151   3321  0.068183    1.252560

paymentmethod

                               mean  count      diff  risk_ratio
paymentmethod
credit_card_(automatic)    0.164339   1217 -0.105630    0.608733
bank_transfer_(automatic)  0.168171   1219 -0.101797    0.622928
mailed_check               0.193870   1305 -0.076098    0.718121
electronic_check           0.455890   1893  0.185922    1.688682

In [42]:
from sklearn.metrics import mutual_info_score

In [43]:
mutual_info_score(df_full_train['churn'], df_full_train['contract'])

0.0983203874041556

In [44]:
mutual_info_score(df_full_train['churn'], df_full_train['gender'])

0.0001174846211139946

In [45]:
def mutual_info_churn(series):
    return mutual_info_score(df_full_train['churn'], series)

In [47]:
mi = df_full_train[categorial_columns].apply(mutual_info_churn).sort_values(ascending=False)

In [48]:
mi

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64